package bedrock_test

import (
	"encoding/json"
	"strings"
	"testing"

	"png-to-mcpack/internal/bedrock"
)

func TestGenerateManifest(t *testing.T) {
	packName := "TestSkinPack"
	desc := "Generated by png-to-mcpack"
	headerUUID := "11111111-1111-4111-8111-111111111111"
	moduleUUID := "22222222-2222-4222-8222-222222222222"

	manifest, err := bedrock.GenerateManifest(packName, desc, headerUUID, moduleUUID)
	if err != nil {
		t.Fatalf("unexpected error generating manifest: %v", err)
	}

	if manifest.FormatVersion != 2 {
		t.Errorf("expected format_version 2, got %d", manifest.FormatVersion)
	}
	if manifest.Header.Name != packName {
		t.Errorf("expected header name %q, got %q", packName, manifest.Header.Name)
	}
	if manifest.Header.UUID != headerUUID {
		t.Errorf("expected header UUID %q, got %q", headerUUID, manifest.Header.UUID)
	}
	if len(manifest.Modules) != 1 {
		t.Fatalf("expected 1 module, got %d", len(manifest.Modules))
	}
	if manifest.Modules[0].Type != "skin_pack" {
		t.Errorf("expected module type 'skin_pack', got %q", manifest.Modules[0].Type)
	}
	if manifest.Modules[0].UUID != moduleUUID {
		t.Errorf("expected module UUID %q, got %q", moduleUUID, manifest.Modules[0].UUID)
	}

	data, err := json.Marshal(manifest)
	if err != nil {
		t.Fatalf("failed to marshal manifest to json: %v", err)
	}
	if len(data) == 0 {
		t.Fatal("manifest json output is empty")
	}
}

func TestGenerateSkinsJSON_BothModels(t *testing.T) {
	skinName := "custom_skin"
	texture := "skin.png"

	skinsCfg, err := bedrock.GenerateSkinsJSON(skinName, texture, bedrock.ModelModeBoth)
	if err != nil {
		t.Fatalf("unexpected error generating skins.json: %v", err)
	}

	if len(skinsCfg.Skins) != 2 {
		t.Fatalf("expected 2 skin entries for dual-model pack, got %d", len(skinsCfg.Skins))
	}

	classic := skinsCfg.Skins[0]
	if classic.LocalizationName != skinName+"_classic" {
		t.Errorf("expected classic localization_name %q, got %q", skinName+"_classic", classic.LocalizationName)
	}
	if classic.Geometry != "geometry.humanoid.custom" {
		t.Errorf("expected classic geometry 'geometry.humanoid.custom', got %q", classic.Geometry)
	}
	if classic.Texture != texture {
		t.Errorf("expected classic texture %q, got %q", texture, classic.Texture)
	}
	if classic.Type != "free" {
		t.Errorf("expected skin type 'free', got %q", classic.Type)
	}

	slim := skinsCfg.Skins[1]
	if slim.LocalizationName != skinName+"_slim" {
		t.Errorf("expected slim localization_name %q, got %q", skinName+"_slim", slim.LocalizationName)
	}
	if slim.Geometry != "geometry.humanoid.customSlim" {
		t.Errorf("expected slim geometry 'geometry.humanoid.customSlim', got %q", slim.Geometry)
	}
	if slim.Texture != texture {
		t.Errorf("expected slim texture %q, got %q", texture, slim.Texture)
	}
	if slim.Type != "free" {
		t.Errorf("expected skin type 'free', got %q", slim.Type)
	}
}

func TestGenerateSkinsJSON_ClassicModel(t *testing.T) {
	skinName := "steve_skin"
	texture := "skin.png"

	skinsCfg, err := bedrock.GenerateSkinsJSON(skinName, texture, bedrock.ModelModeClassic)
	if err != nil {
		t.Fatalf("unexpected error generating skins.json: %v", err)
	}

	if len(skinsCfg.Skins) != 1 {
		t.Fatalf("expected 1 skin entry, got %d", len(skinsCfg.Skins))
	}
	skin := skinsCfg.Skins[0]
	if skin.LocalizationName != skinName {
		t.Errorf("expected localization_name %q, got %q", skinName, skin.LocalizationName)
	}
	if skin.Geometry != "geometry.humanoid.custom" {
		t.Errorf("expected classic geometry 'geometry.humanoid.custom', got %q", skin.Geometry)
	}
	if skin.Texture != texture {
		t.Errorf("expected texture %q, got %q", texture, skin.Texture)
	}
	if skin.Type != "free" {
		t.Errorf("expected skin type 'free', got %q", skin.Type)
	}
}

func TestGenerateSkinsJSON_SlimModel(t *testing.T) {
	skinName := "alex_skin"
	texture := "skin.png"

	skinsCfg, err := bedrock.GenerateSkinsJSON(skinName, texture, bedrock.ModelModeSlim)
	if err != nil {
		t.Fatalf("unexpected error generating skins.json: %v", err)
	}

	if len(skinsCfg.Skins) != 1 {
		t.Fatalf("expected 1 skin entry, got %d", len(skinsCfg.Skins))
	}
	skin := skinsCfg.Skins[0]
	if skin.LocalizationName != skinName {
		t.Errorf("expected localization_name %q, got %q", skinName, skin.LocalizationName)
	}
	if skin.Geometry != "geometry.humanoid.customSlim" {
		t.Errorf("expected slim geometry 'geometry.humanoid.customSlim', got %q", skin.Geometry)
	}
}

func TestGenerateLang_BothModels(t *testing.T) {
	skinName := "my_skin"
	lang := bedrock.GenerateLang(skinName, bedrock.ModelModeBoth)

	expectedSkinPack := "skinpack.my_skin=my_skin"
	expectedClassic := "skin.my_skin.my_skin_classic=my_skin (Classic)"
	expectedSlim := "skin.my_skin.my_skin_slim=my_skin (Slim)"

	if !strings.Contains(lang, expectedSkinPack) {
		t.Fatalf("expected lang to contain %q, got: %s", expectedSkinPack, lang)
	}
	if !strings.Contains(lang, expectedClassic) {
		t.Fatalf("expected lang to contain %q, got: %s", expectedClassic, lang)
	}
	if !strings.Contains(lang, expectedSlim) {
		t.Fatalf("expected lang to contain %q, got: %s", expectedSlim, lang)
	}
}

func TestGenerateLang_SingleModel(t *testing.T) {
	skinName := "my_skin"
	lang := bedrock.GenerateLang(skinName, bedrock.ModelModeClassic)

	expectedSkinPack := "skinpack.my_skin=my_skin"
	expectedSkin := "skin.my_skin.my_skin=my_skin"

	if !strings.Contains(lang, expectedSkinPack) || !strings.Contains(lang, expectedSkin) {
		t.Fatalf("expected lang to contain %q and %q, got: %s", expectedSkinPack, expectedSkin, lang)
	}
}
