package bedrock_test

import (
	"encoding/json"
	"testing"

	"png-to-mcpack/internal/bedrock"
)

func TestGenerateManifest(t *testing.T) {
	packName := "TestSkinPack"
	desc := "Generated by png-to-mcpack"
	headerUUID := "11111111-1111-4111-8111-111111111111"
	moduleUUID := "22222222-2222-4222-8222-222222222222"

	manifest, err := bedrock.GenerateManifest(packName, desc, headerUUID, moduleUUID)
	if err != nil {
		t.Fatalf("unexpected error generating manifest: %v", err)
	}

	if manifest.FormatVersion != 2 {
		t.Errorf("expected format_version 2, got %d", manifest.FormatVersion)
	}
	if manifest.Header.Name != packName {
		t.Errorf("expected header name %q, got %q", packName, manifest.Header.Name)
	}
	if manifest.Header.UUID != headerUUID {
		t.Errorf("expected header UUID %q, got %q", headerUUID, manifest.Header.UUID)
	}
	if len(manifest.Modules) != 1 {
		t.Fatalf("expected 1 module, got %d", len(manifest.Modules))
	}
	if manifest.Modules[0].Type != "skin_pack" {
		t.Errorf("expected module type 'skin_pack', got %q", manifest.Modules[0].Type)
	}
	if manifest.Modules[0].UUID != moduleUUID {
		t.Errorf("expected module UUID %q, got %q", moduleUUID, manifest.Modules[0].UUID)
	}

	data, err := json.Marshal(manifest)
	if err != nil {
		t.Fatalf("failed to marshal manifest to json: %v", err)
	}
	if len(data) == 0 {
		t.Fatal("manifest json output is empty")
	}
}

func TestGenerateSkinsJSON_ClassicModel(t *testing.T) {
	skinName := "steve_skin"
	texture := "skin.png"

	skinsCfg, err := bedrock.GenerateSkinsJSON(skinName, texture, false)
	if err != nil {
		t.Fatalf("unexpected error generating skins.json: %v", err)
	}

	if len(skinsCfg.Skins) != 1 {
		t.Fatalf("expected 1 skin entry, got %d", len(skinsCfg.Skins))
	}
	skin := skinsCfg.Skins[0]
	if skin.Geometry != "geometry.humanoid.custom" {
		t.Errorf("expected classic geometry 'geometry.humanoid.custom', got %q", skin.Geometry)
	}
	if skin.Texture != texture {
		t.Errorf("expected texture %q, got %q", texture, skin.Texture)
	}
	if skin.Type != "free" {
		t.Errorf("expected skin type 'free', got %q", skin.Type)
	}
}

func TestGenerateSkinsJSON_SlimModel(t *testing.T) {
	skinName := "alex_skin"
	texture := "skin.png"

	skinsCfg, err := bedrock.GenerateSkinsJSON(skinName, texture, true)
	if err != nil {
		t.Fatalf("unexpected error generating skins.json: %v", err)
	}

	if len(skinsCfg.Skins) != 1 {
		t.Fatalf("expected 1 skin entry, got %d", len(skinsCfg.Skins))
	}
	skin := skinsCfg.Skins[0]
	if skin.Geometry != "geometry.humanoid.customSlim" {
		t.Errorf("expected slim geometry 'geometry.humanoid.customSlim', got %q", skin.Geometry)
	}
}

func TestGenerateLang(t *testing.T) {
	skinName := "my_skin"
	lang := bedrock.GenerateLang(skinName)

	expectedSkinPack := "skinpack.my_skin=my_skin"
	expectedSkin := "skin.my_skin.my_skin=my_skin"

	if !containsSubstring(lang, expectedSkinPack) || !containsSubstring(lang, expectedSkin) {
		t.Fatalf("expected lang to contain %q and %q, got: %s", expectedSkinPack, expectedSkin, lang)
	}
}

func containsSubstring(s, sub string) bool {
	return len(s) >= len(sub) && (s == sub || (len(s) > len(sub) && (s[:len(sub)] == sub || s[len(s)-len(sub):] == sub || findSub(s, sub))))
}

func findSub(s, sub string) bool {
	for i := 0; i <= len(s)-len(sub); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}
